on:
  push:
    branches: [ "main" ]
jobs:
  print_npm_i:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print npm i
        working-directory: ./api
        run: npm i 