# on:
#   push:
#     branches: ["main"]
# jobs:
#   print_npm_i :
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - id: print_npm_i
#         working-directory: ./api
#         shell: bash
#         run: |
#           OUTPUT=`npm i`
#           echo outputContent=$OUTPUT >> $GITHUB_OUTPUT
#       - id: print_npm_i_2
#         run: echo "${{steps.print_npm_i.outputs.outputContent}}"
         

      #      - name: build inf
      # working-directory: ./aws
      # run: |
      #    terraform init
      #    terraform destroy -auto-approve


on:
  push:
    branches: ["main"]
jobs:
  ci_cd :
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag geri007/api:1.0.0
    - name: login to aws 
      run: |
         aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY}}
         aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY}}
         aws configure set region eu-central-1
         aws configure set output "json"
    - name: init terraform
      working-directory: ./aws
      run: terraform init
    - id: build_erc_repo_save_output
      working-directory: ./aws
      shell: bash
      run: |
       terraform apply -target module.ecr -auto-approve
       echo outputContent=`terraform output ecrRepo` >> $GITHUB_OUTPUT
    - id: show_the_output
      shell: bash
      run: echo "${{steps.build_erc_repo_save_output.outputContent}}"
      

         
         